# Generated by Django 4.0.4 on 2022-04-17 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organization.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='organization', max_length=15)),
                ('full_name', models.CharField(max_length=255)),
                ('open_year', models.IntegerField()),
                ('full_address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('organization_type', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.CharField(choices=[('Andijon', 'Andijon viloyati'), ('Buxoro', 'Buxoro viloyati'), ("Farg'ona", "Farg'ona viloyati"), ('Jizzax', 'Jizzax viloyati'), ('Namangan', 'Namangan viloyati'), ('Navoiy', 'Navoiy viloyati'), ("Qoraqolpog'iston", "Qoraqalpog'iston Respublikasi"), ('Qashqadaryo', 'Qashqadaryo viloyati'), ('Samarqand', 'Samarqand viloyati'), ('Sirdaryo', 'Sirdaryo viloyati'), ('Surxondaryo', 'Surxondaryo viloyati'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Toshkent shahri', 'Toshkent shahri'), ('Xorazm', 'Xorazm viloyati')], max_length=70)),
                ('organization_pic', models.ImageField(upload_to=organization.models.path_and_rename_organization, verbose_name='Organization Picture')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
