# Generated by Django 4.0.4 on 2022-04-19 01:40

from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('library', '0006_library_user_type_alter_library_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, unique=True)),
                ('body', models.TextField(max_length=500)),
                ('events_pic', models.ImageField(upload_to=main_app.models.path_and_rename_events, verbose_name='News Picture')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('address', models.TextField(max_length=50)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, unique=True)),
                ('body', models.TextField(max_length=500)),
                ('news_pic', models.ImageField(upload_to=main_app.models.path_and_rename_news, verbose_name='News Picture')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_file', models.FileField(upload_to=main_app.models.path_and_rename_file)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('state', models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Qabul qilindi', 'Qabul qilindi'), ('Bekor qilindi', 'Bekor qilindi')], default='Kutilmoqda', max_length=50)),
                ('help', models.CharField(choices=[('Hamkorlik', 'Hamkorlik'), ('Homiylik', 'Homiylik'), ("Beg'araz yordam", "Beg'araz yordam")], default='Hamkorlik', max_length=50)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.library')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
