# Generated by Django 4.0.4 on 2022-04-14 05:55

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, unique=True)),
                ('body', models.TextField(max_length=500)),
                ('news_pic', models.ImageField(upload_to=main_app.models.path_and_rename_events, verbose_name='News Picture')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('address', models.TextField(max_length=50)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, unique=True)),
                ('body', models.TextField(max_length=500)),
                ('news_pic', models.ImageField(upload_to=main_app.models.path_and_rename_news, verbose_name='News Picture')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
