# Generated by Django 4.0.4 on 2022-04-14 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='news_pic',
            new_name='events_pic',
        ),
    ]
